### ISSUE TITLE
HTML5-Attribut @data-xy in Selectbox

### ISSUE THREAD

**Issue by StefanDumont** [torstenroeder/flotilla#1]
Die Selectboxen, die kein value-Attribut tragen, könnten ihren Wert zusätzlich auch im HTML5-Attribut "data-[irgendein-name]" tragen. Dadurch wäre z.B. möglich, per CSS Bilder für jede option einzublenden ...

Weitere Infos zum Attribut:
http://html5doctor.com/html5-custom-data-attributes/

**Comment by torstenroeder** [comment]
So, jetzt wird das Value-Attribut in <option> IMMER gesetzt, somit sollte es jetzt auch gehen ...
