### ISSUE TITLE
Does not work with column names containing spaces

### ISSUE THREAD

**Issue by Rillke** [torstenroeder/flotilla#9]
Reproducing: Create a form and do:

```
$form->addField ('profession',SELECT)             ->setLabel ('profession')
    ->addOptionsFromTable ( 'nmv__professions', 'ID professions', 'profession');
```

Note the space in the database ID column.

Result:

```
Fatal error: Uncaught Error: Call to a member function fetch_object() on boolean in /var/www/html/flotilla/classes/field_select.php:69 Stack trace: #0 /var/www/html/nmv_edit_victim.php(32): Field_Select->addOptionsFromTable('nmv__profession...', 'ID professions', 'profession') #1 {main} thrown in /var/www/html/flotilla/classes/field_select.php on line 69
```

Expected result:
HTML select element.

**Comment by torstenroeder** [comment]
Concerning the project: I think we excluded spaces from column names?

**Comment by torstenroeder** [comment]
Some ` were missing in the relevant function. Can you check again?

**Comment by torstenroeder** [comment]
I needed to revert this. Values like concatenated fields (especially for the title parameter) would then be impossible.
Solution here:     ->addOptionsFromTable ( 'nmv__professions', '´ID professions´', 'profession');

**Comment by Rillke** [comment]
> Concerning the project: I think we excluded spaces from column names?

Yes, we did. So we do not need to fix it as part of that project. However, in general this is unexpected or needs documentation.

**Comment by torstenroeder** [comment]
Ok, good. I put it in the Wiki:
https://github.com/torstenroeder/flotilla/wiki/Select-Lists
